# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @name gibbs_sampleC
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @return a random sample of size \code{n}
#' @export
NULL

gibbs_sampleC <- function(N, a, b, n, thin) {
    .Call('_StatComp21086_gibbs_sampleC', PACKAGE = 'StatComp21086', N, a, b, n, thin)
}

